name: Runner

on:
  #schedule:
  # - cron: "0 22 * * *" #Github Action使用的时间为UTC时间，中国使用UTC+8，所对应的是北京时间早6:00，但由于任务排队等原因，实际执行时间为6:20左右，如有需要可更改
  watch:
    types: [started]

env:
    SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
    SMTP_PORT: ${{ secrets.SMTP_PORT }}
    SMTP_USER: ${{ secrets.SMTP_USER }}
    SMTP_PASSWD: ${{ secrets.SMTP_PASSWD }}
    SMTP_MAILTO: ${{ secrets.SMTP_MAILTO }}
    IMEI: ${{ secrets.IMEI }}


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Actions
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        check-latest: true

    - name: Run
      run: |
        python3 --version
        python3 -m pip install requests rich
        python3 main.py
